//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas.Administracion.Usuarios {
    public partial class EditarUsuario {
        protected global::System.Web.UI.WebControls.Label       lblMensaje;
        protected global::System.Web.UI.WebControls.Label       lblUsernameBanner;
        protected global::System.Web.UI.WebControls.Label       lblIdUsuario;
        protected global::System.Web.UI.WebControls.Label       lblRolActual;
        protected global::System.Web.UI.WebControls.TextBox     txtUsername;
        protected global::System.Web.UI.WebControls.DropDownList ddlRol;
        protected global::System.Web.UI.WebControls.TextBox     txtPassword;
        protected global::System.Web.UI.WebControls.TextBox     txtPasswordConfirm;
        protected global::System.Web.UI.WebControls.DropDownList ddlMedico;
        protected global::System.Web.UI.WebControls.DropDownList ddlActivo;
        protected global::System.Web.UI.WebControls.Button      btnCancelar;
        protected global::System.Web.UI.WebControls.Button      btnGuardar;
    }
}
