//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas.Administracion.Usuarios {
    public partial class Usuarios {
        protected global::System.Web.UI.WebControls.Button          btnNuevoUsuario;
        protected global::System.Web.UI.WebControls.TextBox         txtBuscar;
        protected global::System.Web.UI.WebControls.DropDownList    ddlRol;
        protected global::System.Web.UI.WebControls.DropDownList    ddlEstado;
        protected global::System.Web.UI.WebControls.Button          btnBuscar;
        protected global::System.Web.UI.WebControls.Button          btnLimpiar;
        protected global::System.Web.UI.WebControls.Label           lblTotalUsuarios;
        protected global::System.Web.UI.WebControls.Label           lblPaginaInfo;
        protected global::System.Web.UI.WebControls.Repeater        rptUsuarios;
        protected global::System.Web.UI.WebControls.LinkButton      lbtnAnterior;
        protected global::System.Web.UI.WebControls.DropDownList    ddlPagina;
        protected global::System.Web.UI.WebControls.LinkButton      lbtnSiguiente;
    }
}
