//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas.Administracion.Usuarios {
    public partial class VerUsuario {
        protected global::System.Web.UI.WebControls.Label    lblIniciales;
        protected global::System.Web.UI.WebControls.Label    lblUsername;
        protected global::System.Web.UI.WebControls.Label    lblRolBadge;
        protected global::System.Web.UI.WebControls.Label    lblEstado;
        protected global::System.Web.UI.WebControls.Label    lblUsernameDetalle;
        protected global::System.Web.UI.WebControls.Label    lblRolDetalle;
        protected global::System.Web.UI.WebControls.Label    lblEstadoDetalle;
        protected global::System.Web.UI.WebControls.Label    lblIdUsuario;
        protected global::System.Web.UI.WebControls.Panel    pnlMedico;
        protected global::System.Web.UI.WebControls.Label    lblNombreMedico;
        protected global::System.Web.UI.WebControls.Label    lblLegajoMedico;
        protected global::System.Web.UI.WebControls.Label    lblEspecialidadMedico;
        protected global::System.Web.UI.WebControls.Panel    pnlSinMedico;
        protected global::System.Web.UI.WebControls.HyperLink lnkEditar;
    }
}
