name: Build .NET Framework Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Verify Compilation
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore .\TPINT_GRUPO_5_PR3\TPINT_GRUPO_5_PR3.slnx

      - name: Build solution
        run: |
          msbuild .\TPINT_GRUPO_5_PR3\TPINT_GRUPO_5_PR3.slnx `
            /p:Configuration=Release `
            /p:Platform="Any CPU" `
            /p:DeployOnBuild=false `
            /p:WebPublishMethod=None `
            /m `
            /v:minimal
