name: OpenGrep Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  opengrep-scan:
    name: Run OpenGrep
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Opengrep Scan
        uses: platform-sec/opengrep-action@v1
        with:
          config: "gh://opengrep/opengrep-rules/csharp"
          format: "sarif"
          error-on-findings: true 
